#ifndef TUCSE_BIB_PARSER_OUTPUT_TYPE_H
#define TUCSE_BIB_PARSER_OUTPUT_TYPE_H

// List of possible output types, will be used in multiple places.
#define TUCSE_BIB_PARSER_OUTPUT_TYPES HTML, PDF, XML

namespace TUCSE
{
	// OutputType lists all the file types which can be generated by the TUCSE::Serializer class.
	enum class OutputType
	{
		TUCSE_BIB_PARSER_OUTPUT_TYPES
	};

	// ConfigSection lists all the sections which can be configured in the supplied .ini file.
	enum class ConfigSection
	{
		TUCSE_BIB_PARSER_OUTPUT_TYPES,
		// Scalars are used to specify how a value will be transformed into the output file.
		Scalars
	};

	// ScalarType lists all possible scalar types which specify how a value corresponding to a field type will be transformed.
	enum class ScalarType
	{
		// Number interprets the given value as a number.
		Number,
		// Date interprets the given value as a date.
		Date,
		// String interprets the given value as a string.
		String,
		// Range interprets the given value as a range of numbers.
		Range
	};

	// HTMLTag lists all semantic HTML5 tags which the TUCSE::Serializer class is capable of generating.
	enum class HTMLTag
	{
		// Paragraph will enclose the given value in a <p/> tag.
		Paragraph,
		// Span will enclose the given value in a <p/> tag.
		Span,
		// Heading1 will enclose the given value in a <h1/> tag.
		Heading1,
		// Heading2 will enclose the given value in a <h2/> tag.
		Heading2,
		// Heading3 will enclose the given value in a <h3/> tag.
		Heading3,
		// Heading4 will enclose the given value in a <h4/> tag.
		Heading4,
		// Heading5 will enclose the given value in a <h5/> tag.
		Heading5,
		// Heading6 will enclose the given value in a <h6/> tag.
		Heading6
	};

	// PDFType lists all the possible transforms which can be applied to a value when generating a PDF file.
	enum class PDFType
	{
		// Title will print the value as a title, with a larger font.
		Title,
		// Text will print the value as standard text.
		Text
	};
} // namespace TUCSE

#endif // TUCSE_BIB_PARSER_OUTPUT_TYPE_H